name: notif_app
description: Sistema corporativo de alertas e compliance.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0' # Mantendo compatibilidade estável

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^8.0.1
  fl_chart: ^1.1.1
  lucide_icons: ^0.257.0  # <--- Use esta versão exatamente
  flutter_riverpod: ^3.2.1
  go_router: ^17.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true